# Hyper parameters
hidden_size : 45 #lower,90 is to high
hidden_layer_depth : 1
latent_length : 20
batch_size : 32
learning_rate : 0.0005
n_epochs : 300
dropout_rate : 0.2
optimizer : 'Adam'  # options: ADAM, SGD
cuda : True  # options: True, False
print_every : 30
clip : True  # options: True, False
max_grad_norm : 5
loss : 'MSELoss'  # options: SmoothL1Loss, MSELoss
block : 'LSTM'  # options: LSTM, GRU
# Mutual information based score
