batch_size: 10
block: LSTM
clip: true
cuda: true
dropout_rate: 0.2
hidden_layer_depth: 1
hidden_size: 30
latent_length: 6
learning_rate: 0.0003
loss: SmoothL1Loss
max_grad_norm: 5
n_epochs: 800
optimizer: Adam
print_every: 60
