batch_size: 32
block: LSTM
clip: true
cuda: true
dropout_rate: 0.2
hidden_layer_depth: 2
hidden_size: 40
latent_length: 15
learning_rate: 0.0005
loss: SmoothL1Loss
max_grad_norm: 5
n_epochs: 300
optimizer: Adam
print_every: 60
