batch_size: 6
block: LSTM
clip: true
cuda: true
dropout_rate: 0.2
hidden_layer_depth: 2
hidden_size: 40
latent_length: 6
learning_rate: 0.0003
loss: SmoothL1Loss
max_grad_norm: 5
n_epochs: 1400
optimizer: Adam
print_every: 60
