batch_size: 120
block: LSTM
clip: true
cuda: true
dropout_rate: 0.2
hidden_layer_depth: 2
hidden_size: 60
latent_length: 5
learning_rate: 0.0003
loss: SmoothL1Loss
max_grad_norm: 5
n_epochs: 1200
optimizer: Adam
print_every: 60
